### ISSUE TITLE
팀프로젝트 주제

### ISSUE THREAD

**Issue by 21800677** [https-github-com-21800677/2022OSS-Teamproject-664677#1]
팀프로젝트 주제를 선정해보려 합니다
CAFE 디저트 자판기
출퇴근 관리 시스템
스터디 카페! 이젠 어디서든 예약할 수 있어요
가계부 프로그램
이중에서 편하신 걸로 하나 골라주세요
물론 여기 없는 주제도 괜찮습니다.
함수 10개 이상 생성해야 한다고 합니다

**Comment by jjas-min** [comment]
cafe 디저트 자판기 어떨까요? 저희가 진행하던 미니프로젝트랑 비슷하게 구현할 수 있을꺼같아요

**Comment by 21800677** [comment]
좋습니다
