### ISSUE TITLE
분업 관련 토의

### ISSUE THREAD

**Issue by 21800677** [https-github-com-21800677/2022OSS-Teamproject-664677#2]
이제 역할을 나눠야 합니다.
먼저 wiki는 간단하게 만들어놨으니 확인해보시고요

**Comment by 21800677** [comment]
일단 저희 자판기의 기능을 먼저 생각해볼까요?

**Comment by jjas-min** [comment]
CRUD / 저장 불러오기 / 메뉴 해서 7가지는 고정이고 3가지 이상 생각해봐야할것같아요

**Comment by 21800677** [comment]
1. 이름에 따른 검색
2. 가격대에 따른 검색

**Comment by 21800677** [comment]
이런거 외에 또 어떤게 있을까요

**Comment by jjas-min** [comment]
구조체 내용부터 정하면 좋을꺼같아요

**Comment by 21800677** [comment]
좋습니다

**Comment by 21800677** [comment]
구조체 주제는 디저트로 하고

**Comment by 21800677** [comment]
이름, 가격, 상세설명 외에 또 뭔가 들어갈 게 있을까요?

**Comment by jjas-min** [comment]
디저트 종류도 케익 / 마카롱 / 쿠키 등등 있으니까 괜찮을껏같네요

**Comment by jjas-min** [comment]
맛도 추가하면 괜찮을꺼같아요

**Comment by jjas-min** [comment]
이름 종류 맛 가격 설명 5가지 어떠신가요?

**Comment by 21800677** [comment]
그럼 
string[] name
string[] expl
int price
int type
int taste

**Comment by 21800677** [comment]
이정도로 할까요?
아니면 taste를 string으로 바꾸는게 좋을까요?

**Comment by jjas-min** [comment]
C라서 char type으로 하고 taste도 string으로 해야할듯해요

**Comment by 21800677** [comment]
넵 좋아요

**Comment by 21800677** [comment]
그럼 함수는 맛, 이름, 종류, 가격대에 따른 검색으로 하는건 어떨까요?

**Comment by jjas-min** [comment]
그럼 검색기능을 5가지 넣는걸로 합시다.

**Comment by jjas-min** [comment]
아 설명은 빼고 갈까요?

**Comment by 21800677** [comment]
그것까지 넣기에는 좀 부담될 것 같아요

**Comment by jjas-min** [comment]
그럼 4가지 넣어서 CRUD / 불러오기 저장하기 / 메뉴 / 맛 이름 종류 가격 으로  함수 구성하도록 합시다.

**Comment by 21800677** [comment]
네 좋습니다
역할은 어떻게 나누실래요?

**Comment by jjas-min** [comment]
CRUD 불러오기 저장하기 메뉴
검색기능 
이렇게 나누어서 역할 나누면 좋을것같은데 혹시 선호하는쪽 있으신가요?

**Comment by 21800677** [comment]
검색기능을 제가 할게요
그리고 제가 미니프로젝트를 제대로 못끝내서 나중에 기존에 완성하신 파일 한번 볼 수 있을까요?

**Comment by jjas-min** [comment]
네 제가 카카오톡으로 올려드릴게요.

**Comment by 21800677** [comment]
그럼 이번 issue는 여기서 닫을게요
분업과 기능도 다 충족됐으니 이번 과제는 다 된 것 같습니다.
readme 파일은 제가 마무리해서 저장할게요
