### ISSUE TITLE
Readme 구성

### ISSUE THREAD

**Issue by jjas-min** [https-github-com-21800677/2022OSS-Teamproject-664677#3]
Readme 파일 구성 논의

**Comment by jjas-min** [comment]
제일 위 제목은 Cafe 디저트 자판기로 하는게 좋을거같아요

**Comment by 21800677** [comment]
그 외에 또 수정할 것 있을까요?
사진이 안어울린다거나 하는 거 있으면 말씀해주세요

**Comment by jjas-min** [comment]
개발 환경은 GCC / C언어 정도로 하면 될거같아요

**Comment by 21800677** [comment]
저희 주문 기능은 없어도 될까요?

**Comment by jjas-min** [comment]
주문해서 총 얼마인지 계산하는 함수도 필요할거같네요..그거까지 맡아주실수 있으신가요?

**Comment by 21800677** [comment]
넵 알겠습니다

**Comment by jjas-min** [comment]
Readme 구성을 제가 조금 수정해서 PR하겠습니다.

**Comment by 21800677** [comment]
네 알겠습니다
그리고 위키는 일단 대충은 만들어놨고 꾸준히 개선하는걸로 하죠

**Comment by jjas-min** [comment]
네 알겠습니다.
