### ISSUE TITLE
Team Project 2 역할 분배

### ISSUE THREAD

**Issue by jjas-min** [https-github-com-21800677/2022OSS-Teamproject-664677#6]
이번 주 업데이트 사항이 

1. 데이터 구조체 및  CRUD 모든 함수 구현 및 git으로 버전 관리

2. 완성된 각 함수를 실행한 화면캡처 업로드 (github repository root에서 /screenshots 폴더 만들어서 이미지 업로드)

3. issue를 사용하여 개발에 필요한 의견 교환

4. WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가)

위 4가지 입니다.

**Comment by jjas-min** [comment]
1번은 CRUD개발이 제 역할이라서 제가 하면 될꺼같은데, 2,4번을 어떻게 할지 의견 주시면 감사하겠습니다.

**Comment by 21800677** [comment]
파일 올려주시면 2번하고 4번은 제가 하겠습니다.

**Comment by 21800677** [comment]
메인은 안만드신거죠?

**Comment by 21800677** [comment]
기존 미니프로젝트 파일 보내주실 수 있나요? 그거 참고해서 메인파일 작성해볼게요

**Comment by jjas-min** [comment]
6시 이후에 보내겠습니다.

**Comment by jjas-min** [comment]
메인 개발해서 올릴 때 fork해서 본인 계정 repo에서 PR하시는게 좋을것같아요

**Comment by 21800677** [comment]
넵 알겠습니다

**Comment by jjas-min** [comment]
메일 보냈습니다 확인해주세요
